open Common
open Lexer
open Parser
open Evaluator


(* Takes a string s and returns the abstract syntax tree generated by lexing and parsing s *)
let parse s =
    let lexbuf = Lexing.from_string s in
        let ast = Parser.clause Lexer.token lexbuf in
            ast
